spring.application.name=ServiceShipping
spring.datasource.name=serviceshipping
spring.datasource.url=jdbc:mysql://localhost:3306/mshippingservice?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
server.port=2206
spring.profiles.active=dev

logging.level.com.netflix.eureka=OFF
logging.level.com.netflix.discovery=OFF

